name: Codecov
on: [ push, pull_request ]
jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Check
        run: gradle check

      - name: Build Code Coverage Report
        run: gradle codeCoverageReport

      - name: Upload Code Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          files: ./build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
          path_to_write_report: ./coverage/codecov_report.txt
